### ISSUE TITLE
Pygmentize does not work out of the box

### ISSUE THREAD

**Issue by jondoesntgit** [mailmate/pygments.mmbundle#1]
I installed pygments using the bundle manager inside of the app. However, I don't see a preview when drafting a new email, nor do I see any pygmentization when I receive an email I send back to myself.

**Comment by jondoesntgit** [comment]
Aha! It needs to be enabled in the compose settings of the app. Perhaps putting a bit about this in the `README.md`?

**Comment by cjoshmartin** [comment]
fixed it
